# Generated by Django 4.0.2 on 2022-07-20 04:29

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_ad1_ad2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', versatileimagefield.fields.VersatileImageField(upload_to='Ad/', verbose_name='Image')),
                ('image2', versatileimagefield.fields.VersatileImageField(upload_to='Ad/', verbose_name='Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI')),
            ],
            options={
                'verbose_name_plural': 'Advertisement',
            },
        ),
        migrations.DeleteModel(
            name='Ad1',
        ),
        migrations.DeleteModel(
            name='Ad2',
        ),
    ]
