# Generated by Django 4.0.2 on 2022-07-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_category_product_sub_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
