# Generated by Django 4.0.2 on 2022-07-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(max_length=225),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
